// Angular - The Complete Guide (2024 Edition)/Section13 Handling User Input and Working with Forms (Template-driven and Reactive)/Reactive-driven way/src/app/auth/signup/signup.component.ts
import { Component } from '@angular/core';
import {
  AbstractControl,
  FormArray,
  FormControl,
  FormGroup,
  ReactiveFormsModule,
  Validators,
} from '@angular/forms';

function equalValues(controlName1: string, controlName2: string) {
  return (control: AbstractControl) => {
    const val1 = control.get(controlName1)?.value;
    const val2 = control.get(controlName2)?.value;

    if (val1 === val2) {
      return null;
    }

    return { passwordsNotEqual: false };
  };
}

@Component({
  selector: 'app-signup',
  standalone: true,
  templateUrl: './signup.component.html',
  styleUrl: './signup.component.css',
  imports: [ReactiveFormsModule],
})
export class SignupComponent {
  form = new FormGroup({
    email: new FormControl('', {
      validators: [Validators.email, Validators.required],
    }),
    passwords: new FormGroup(
      {
        password: new FormControl('', {
          validators: [Validators.minLength(6), Validators.required],
        }),
        confirmPassword: new FormControl('', {
          validators: [Validators.minLength(6), Validators.required],
        }),
      },
      {
        validators: [equalValues('password', 'confirmPassword')],
      }
    ),
    firstName: new FormControl('', {
      validators: [Validators.required],
    }),
    lastName: new FormControl('', {
      validators: [Validators.required],
    }),
    address: new FormGroup({
      street: new FormControl('', {
        validators: [Validators.required],
      }),
      number: new FormControl('', {
        validators: [Validators.required],
      }),
      postalCode: new FormControl('', {
        validators: [Validators.required],
      }),
      city: new FormControl('', {
        validators: [Validators.required],
      }),
    }),
    role: new FormControl<
      'student' | 'teacher' | 'employee' | 'founder' | 'other'
    >('student', {
      validators: [Validators.required],
    }),
    source: new FormArray([
      new FormControl(false),
      new FormControl(false),
      new FormControl(false),
    ]),
    agree: new FormControl(false, {
      validators: [Validators.required],
    }),
  });

  onSubmit() {
    if (this.form.invalid) {
      console.log('INVALID FORM');
      return;
    }

    console.log(this.form);
  }

  onReset() {
    this.form.reset();
  }
}

<form [formGroup]="form" (ngSubmit)="onSubmit()">
  <h2>Welcome on board!</h2>
  <p>We just need a little bit of data from you to get you started 🚀</p>

  <div class="control">
    <label for="email">Email</label>
    <input id="email" type="email" name="email" formControlName="email" />
    @if (form.controls.email.dirty && form.controls.email.invalid &&
    form.controls.email.touched) {
    <p class="control-error">Please enter a valid email address.</p>
    }
  </div>

  <div class="control-row" formGroupName="passwords">
    <div class="control">
      <label for="password">Password</label>
      <input
        id="password"
        type="password"
        name="password"
        formControlName="password"
      />
    </div>

    <div class="control">
      <label for="confirm-password">Confirm Password</label>
      <input
        id="confirm-password"
        type="password"
        name="confirm-password"
        formControlName="confirmPassword"
      />
    </div>
  </div>

  <hr />

  <div>
    <div class="control-row">
      <div class="control">
        <label for="first-name">First Name</label>
        <input
          type="text"
          id="first-name"
          name="first-name"
          formControlName="firstName"
        />
      </div>

      <div class="control">
        <label for="last-name">Last Name</label>
        <input
          type="text"
          id="last-name"
          name="last-name"
          formControlName="lastName"
        />
      </div>
    </div>

    <fieldset formGroupName="address">
      <legend>Your Address</legend>

      <div class="control-row">
        <div class="control">
          <label for="street">Street</label>
          <input
            type="text"
            id="street"
            name="street"
            formControlName="street"
          />
        </div>

        <div class="control">
          <label for="number">Number</label>
          <input
            type="text"
            id="number"
            name="number"
            formControlName="number"
          />
        </div>
      </div>

      <div class="control-row">
        <div class="control">
          <label for="postal-code">Postal Code</label>
          <input
            type="text"
            id="postal-code"
            name="postal-code"
            formControlName="postalCode"
          />
        </div>

        <div class="control">
          <label for="city">City</label>
          <input type="text" id="city" name="city" formControlName="city" />
        </div>
      </div>
    </fieldset>
  </div>

  <hr />

  <div class="control-row">
    <div class="control">
      <label for="role">What best describes your role?</label>
      <select id="role" name="role" formControlName="role">
        <option value="student">Student</option>
        <option value="teacher">Teacher</option>
        <option value="employee">Employee</option>
        <option value="founder">Founder</option>
        <option value="other">Other</option>
      </select>
    </div>
  </div>

  <fieldset formArrayName="source">
    <legend>How did you find us?</legend>
    <div class="control">
      <input
        type="checkbox"
        id="google"
        name="acquisition"
        value="google"
        formControlName="0"
      />
      <label for="google">Google</label>
    </div>

    <div class="control">
      <input
        type="checkbox"
        id="friend"
        name="acquisition"
        value="friend"
        formControlName="1"
      />
      <label for="friend">Referred by friend</label>
    </div>

    <div class="control">
      <input
        type="checkbox"
        id="other"
        name="acquisition"
        value="other"
        formControlName="2"
      />
      <label for="other">Other</label>
    </div>
  </fieldset>

  <div class="control-row">
    <div class="control">
      <label for="terms-and-conditions">
        <input
          type="checkbox"
          id="terms-and-conditions"
          name="terms"
          formControlName="agree"
        />
        I agree to the terms and conditions
      </label>
    </div>
  </div>

  <p class="form-actions">
    <button type="reset" class="button button-flat" (click)="onReset()">
      Reset
    </button>
    <button type="submit" class="button">Sign up</button>
  </p>
  @if (form.dirty && form.touched && form.invalid) {
  <p class="control-error">Invalid fom - please check your input data.</p>
  }
</form>

// React - The Complete Guide (incl. Next.js, Redux)/Section-17/01-starting-project/src/components/Signup.jsx
export default function Signup() {
  function handleSubmit(event) {
    event.preventDefault();

    const formData = new FormData(event.target);
    const acquisitionChannel = formData.getAll("acquisition");
    const data = Object.fromEntries(formData.entries());
    data.acquisition = acquisitionChannel;

    console.log(data);
    
  }

  return (
    <form onSubmit={(event) => handleSubmit(event)}>
      <h2>Welcome on board!</h2>
      <p>We just need a little bit of data from you to get you started 🚀</p>

      <div className="control">
        <label htmlFor="email">Email</label>
        <input id="email" type="email" name="email" />
      </div>

      <div className="control-row">
        <div className="control">
          <label htmlFor="password">Password</label>
          <input id="password" type="password" name="password" />
        </div>

        <div className="control">
          <label htmlFor="confirm-password">Confirm Password</label>
          <input
            id="confirm-password"
            type="password"
            name="confirm-password"
          />
        </div>
      </div>

      <hr />

      <div className="control-row">
        <div className="control">
          <label htmlFor="first-name">First Name</label>
          <input type="text" id="first-name" name="first-name" />
        </div>

        <div className="control">
          <label htmlFor="last-name">Last Name</label>
          <input type="text" id="last-name" name="last-name" />
        </div>
      </div>

      <div className="control">
        <label htmlFor="phone">What best describes your role?</label>
        <select id="role" name="role">
          <option value="student">Student</option>
          <option value="teacher">Teacher</option>
          <option value="employee">Employee</option>
          <option value="founder">Founder</option>
          <option value="other">Other</option>
        </select>
      </div>

      <fieldset>
        <legend>How did you find us?</legend>
        <div className="control">
          <input
            type="checkbox"
            id="google"
            name="acquisition"
            value="google"
          />
          <label htmlFor="google">Google</label>
        </div>

        <div className="control">
          <input
            type="checkbox"
            id="friend"
            name="acquisition"
            value="friend"
          />
          <label htmlFor="friend">Referred by friend</label>
        </div>

        <div className="control">
          <input type="checkbox" id="other" name="acquisition" value="other" />
          <label htmlFor="other">Other</label>
        </div>
      </fieldset>

      <div className="control">
        <label htmlFor="terms-and-conditions">
          <input type="checkbox" id="terms-and-conditions" name="terms" />I
          agree to the terms and conditions
        </label>
      </div>

      <p className="form-actions">
        <button type="reset" className="button button-flat">
          Reset
        </button>
        <button type="submit" className="button">
          Sign up
        </button>
      </p>
    </form>
  );
}
